[package]
name = "gis-demo"
version = "0.1.0"
edition = "2021"

[dependencies]
databend-driver = "0.24.4"
databend-sql = "0.18.3"
serde_json = "1.0.85"
rocket = { version = "0.5.1", features = ["json"] }

